/* The Pig Game
GAME RULES:

- The game has 2 players, playing in rounds
- In each turn, a player rolls a dice as many times as he whishes. Each result get added to 
  his ROUND score
- BUT, if the player rolls a 1, all his ROUND score gets lost. After that, it's the next 
  player's turn
- The player can choose to 'Hold', which means that his ROUND score gets added to his GLOBAL 
  score. After that, it's the next player's turn
- The first player to reach 100 points on GLOBAL score wins the game

*/

/********************************************************************************************
 * What we'll learn:
 * 1. How to use ternary operators
 * 2. How to add, remove & toggle HTML classes for an element
 */

// We generally write variable declarations on top for a small project, so that the code 
// seems uniform and simple to navigate.
var scores, roundScore, activePlayer;
scores = [0,0];
roundScore = 0;
activePlayer = 0;   //  0 => Player-1;  1 => Player-2

// Hide the dice image when opening the page for the first time
document.querySelector('.dice').style.display = "none";

document.getElementById("score-0").textContent = "0";   // Set Initial Score for Player 1 = 0
document.getElementById("score-1").textContent = "0";   // Set Initial Score for Player 2 = 0
document.getElementById("current-0").textContent = "0"; //Init Overall Score for Player 1 = 0
document.getElementById("current-1").textContent = "0"; //Init Overall Score for Player 2 = 0

// Event Handler for Rolling the Dice
document.querySelector(".btn-roll").addEventListener("click", function() {
    // 1. Generate a Random Number for the dice:
    var dice = Math.floor(Math.random() * 6) + 1;

    // 2. Display the Result
    var diceDOM = document.querySelector(".dice");
    
    // Since the diceDOM is an <img> element, we can access its src attribute as a property
    diceDOM.src = "./img/dice-" + dice + ".png";
    diceDOM.style.display = "block";
    
    // 3. Update the roundScore iff dice !== 1
    if(dice !== 1) {    // When we don't roll a 1
        
        /* Add the score generated by the dice to the roundScore: */
        roundScore += dice;

        /* Display the roundScore to the current activePlayer's temporary score holder */
        document.getElementById("current-" + activePlayer).textContent = roundScore;

    } else {    // When we roll a 1

        /* Change the activePlayer using the ternary operator */
        activePlayer = activePlayer === 0 ? 1 : 0;
        
        /* Reset the roundScore to 0 */
        roundScore = 0;

        /* Set the current scores of both Players (P1 & P2) to 0 */
        document.getElementById("current-0").textContent = 0;
        document.getElementById("current-1").textContent = 0;

        /**
         * Apply the active class to emphasize the current player who has the current turn
         * to throw the die using the classList property as follows: 
         */
        // if (activePlayer === 0) {   // P1's turn
        //     document.querySelector(".player-1-panel").classList.remove("active");
        //     document.querySelector(".player-0-panel").classList.add("active");
        // } else {
        //     document.querySelector(".player-1-panel").classList.add("active");
        //     document.querySelector(".player-0-panel").classList.remove("active");
        // }
        /**
         * The code above is too big and tedious. Instead, we just use a single toggle() 
         * method in the classList property as follows: 
         */
        document.querySelector(".player-1-panel").classList.toggle("active");
        document.querySelector(".player-0-panel").classList.toggle("active");
        /**
         * toggle() method will remove the .active class from the intended element, if it 
         * was applied to the element before, and it will apply the .active class to the
         * intended element if it was not applied to the intended element. 
         */

        /* Hide the dice image when we roll a 1 */
        document.querySelector(".dice").style.display = "none";
    }
});

// Event Handler for Showing the Rules
document.querySelector("#rules").addEventListener('click', function() {
    var rule = [];
    rule[0] = "The game has 2 players, playing in rounds (By default, Player 1 starts)";
    rule[1] = "In each turn, a player rolls a dice as many times as s/he wishes. Each die roll's result gets added to their ROUND score";
    rule[2] = "BUT, if the player rolls a 1, entire ROUND score accumulated till now, becomes 0. After that, it's the next player's turn";
    rule[3] = "The player can choose to 'Hold', which means that the current player's ROUND score gets added to their GLOBAL score. After that, it's the next player's turn";
    rule[4] = "The first player to reach 100 points on GLOBAL score wins the game";
    
    var showAlert = function(messageList) {
        var messageString = "";
        for(var i = 0; i < messageList.length; ++i)
            messageString += (i + 1) + ". " + messageList[i] + ".\n";
        alert(messageString);
    }
    showAlert(rule);
});